config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/pdb-dbv5"

  # Names of training and testing file(s) to be read and processed.
  file_names:
    train: [ "train.cpkl" ]
    test: [ "test.cpkl" ]

classification_settings:
  n_iterations: 5
  models:
    - name: "lr"
      active: True
      C: [0.01, 0.03, 0.1, 0.3, 1, 3]

    - name: "rf"
      active: True
      n_estimators: [10, 50, 100, 500, 1000]
      max_depth: [3, 5]


output_settings:
  output_dir: "output/raw/20230331"
  prefix: ""   # default: none; default file name = <model_name>_<param_name><param_val>_n<n_iterations>_<output_prefix>_output.csv
  # example: lr_c0.1_n5_output.csv