config_type: "evaluation" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "output/raw"

  file_names:
    # experiment_name (to be used as a key in comparative analysis): file_name
    "LR": "20230403/pdb-dbv5_lr_output.csv"
    "RF": "20230403/pdb-dbv5_rf_output.csv"
    "GCN-FFN": "20230404/pdb-dbv5-gnn_gcn_ff_output.csv"

evaluation_settings:
  pos_label: 1
  neg_label: -1
  # metrics
  auroc: True
  auprc: True
  f1: True
  accuracy: True


output_settings:
  output_dir: "output"
  evaluation_dir: "evaluation"
  visualization_dir: "visualizations"
  dataset_dir: "20230403"
  prefix: "pdb-dbv5"# default: none; default file name = <output_prefix>_<model_name>_output.csv